### ISSUE TITLE
Right drag with constant speed sometimes do not activate rotation.

### ISSUE THREAD

**Issue by TextusGames** [SpectralVectors/RightMouseNavigation#10]
Hello sometimes I drag my mouse with right button holded and  camera is not rotating until I stop dragging adn drag again.
It is very unconvinient bug.

**Comment by TextusGames** [comment]
Actually it happens even withoug addon. So it is a blender problem.

**Comment by SpectralVectors** [comment]
Hi Textus, you might already know this, but you can adjust some of Blender's drag thresholds in:

Edit > Preferences > Input > Mouse Drag Threshold & Drag Threshold

and

Edit > Preferences > Navigation > Fly & Walk > Walk > Mouse Sensitivity

Hopefully one of those can help out a bit!
