### ISSUE TITLE
It doesn't look to work in object mode for Blender 3.0

### ISSUE THREAD

**Issue by renejensen** [SpectralVectors/RightMouseNavigation#12]
It doesn't look to work in object mode for Blender 3.0

**Comment by JamesO2x** [comment]
I'm not the creator of this add-on, but it definitely does work in 3.0. I use it daily in my 3.0 workflow, and in 3.1 too. You might have some sort of add-on conflicting with it.

I did have issues with this add-on when upgrading from 3.0 to 3.1 (using the "import my settings from 3.0" button). But uninstalling 3.1 and doing a clean "factory default" install of 3.1 fixed the issue.

So my guess is either you have an add-on conflicting with RightMouseNavigation, or you recently upgraded to 3.0 from a previous version and your settings got messed up in the process. (apparently this happens a lot when switching to new Blender versions, according to a few different people on the Blender Chat)

**Comment by renejensen** [comment]
Wau JamesO2x
That worked. Thanks a lot. It safed my day.

**Comment by JamesO2x** [comment]
I'm glad it helped.
