### ISSUE TITLE
Windll missing on Linux...  Not working in Linux

### ISSUE THREAD

**Issue by Dallco** [SpectralVectors/RightMouseNavigation#13]
attributeError: module ctypes has no attribute 'windll'

Looks like windows only addon.

**Comment by SpectralVectors** [comment]
Yes, unfortunately, for the moment.
If you know how to replace the windll calls with appropriate calls for Linux, then I can merge your code, but I've only recently started to use Linux myself, and I haven't been able to port this addon yet.
I'd love to have access to it on Linux as well, maybe once I've got a couple of projects off my plate I can return to this and get Linux (and maybe Mac) functionality working, too.
Thanks for the interest, I'll update this thread once I've got a Linux version working.

**Comment by Premik** [comment]
I've just commented the three `ctypes.windll.user32..` lines in the `RightMouseNavigation.py` out. And it seems to be working. Not sure what these calls were supposed to do. Perhaps something which is not needed on Linux..

**Comment by keeperofkey** [comment]
> I've just commented the three `ctypes.windll.user32..` lines in the `RightMouseNavigation.py` out. And it seems to be working. Not sure what these calls were supposed to do. Perhaps something which is not needed on Linux..

I can confirm this also worked for me

**Comment by SpectralVectors** [comment]
Very interesting, I had to call a 'fake' right mouse click because the right mouse release event wasn't being detected, but apparently that's just a Windows issue!
Lol, I haven't had a chance to test it out, but at some point I'll update so there's a check for OS and it will only insert the windll calls on Windows.
Thanks for the heads up!

**Comment by SpectralVectors** [comment]
Hi Premik and Dallco, I've added a flag that checks the user's OS and only calls the windll on Windows.
You're right that Linux doesn't need it, and the addon works fine without it.
(It's still a bit of a mystery why it's needed on Windows in the first place TBH).
Thanks!
