### ISSUE TITLE
Orthographic view

### ISSUE THREAD

**Issue by grahamwheaton** [SpectralVectors/RightMouseNavigation#17]
When working in orthographic views, if you right click for the context menu it knocks you out of ortho view - back into perspective view. This can be a bit jarring to workflow. I don't suppose there is a fix for this (minor) issue?

Thanks for the great addon, it makes jumping between UE and Blender much easier.

**Comment by SpectralVectors** [comment]
I would have to test this again to be sure, but AFAIK you can't use Walk/Fly Navigation (the Blender function that makes the addon work) in an orthographic view. Or, at least, when I was testing it, I would always get kicked back into perspective view as soon as I entered navigation.

It's worth a look to see if this can be addressed, I'll check it out for the next update (whenever that comes, lol). Thanks for the feedback!

**Comment by grahamwheaton** [comment]
Forgive my ignorance with coding, but if it is when using the right click menu, could it be made so so it checks if you are in orphographic mode beforehand then turns it back after the action has happen?

**Comment by SpectralVectors** [comment]
Hi graham, I've just added a feature that will return you to Orthographic view after navigation.
I'm closing the issue, thanks for bringing it to my attention, feel free to reopen if it's not working.
Thanks!
