### ISSUE TITLE
Does it work in Blender 3.5.0 ?

### ISSUE THREAD

**Issue by huRwww** [SpectralVectors/RightMouseNavigation#18]
Hello.
I'm using Blender 3.5.0 at steam version.
I've installed this addon via Edit> preferences > install > Select 'RightMouseNavigation.zip' file.
But  pushing WASD while holding RMB doesn't work at all.
Is this my personal problem? or doesn't anyone use Blender 3.5.0 yet?

**Comment by SpectralVectors** [comment]
I tested it on the 3.5 installer version on Windows 10 and it works.
I haven't tried the Steam version yet, I will check and get back to you if there are errors.
It currently only works in Windows (unless you modify it slightly, but the Mac/Linux behavior is not identical to the Windows version)
I also used it with the 3.5 beta version without issues.
I've never looked into the Steam version to see if it handles/stores things in a different way. but it is a possibility.
I'll let you know if I can reproduce your issue.
Thanks for letting me know!

**Comment by SpectralVectors** [comment]
OK, I downloaded the Steam version and it worked for me, tried uninstalling, rebooting and reinstalling, still works without issue.
After installing the addon, did you enable it? (Click the checkbox in Preferences > Addons next to the addon name?)
Are you using Right Mouse Select?
Have you modified your keymap?
I'm not aware of any conflicts with existing addons, but some users have 100s of addons enabled, so its possible there could be a compatibility issue if you have a lot of addons already enabled.

Those are the only things I can think that might cause an issue for you, and the addon should update your keymap automatically when you install it.
Try uninstalling the addon, closing and reopening Blender and reinstalling it and reenabling it.
I'm assuming you're on Windows, but, if not, that would cause some issues. (though I can provide you with a hacky workaround)
Let me know if you have any luck getting it working!

**Comment by huRwww** [comment]
Thank you for effort.
Sorry for missing important information.
I'm using 'Windows 11 Home 64bit' OS.

1. Addon, did you enabel it?
 => I've checked the checkbox in preferences > Add-ons > 'View 3D: Right Mouse Navigation'. So I can see the option 'Time Threshold' and 'Distance THreshold'
2. Are you using RMB Select?
 =>  I'm using LMB selection.
3. Have you modified your keymap?
 => Yes, some of them are modified.  I've suspect that the 'Walk/Fly' hotkey makes the problem, but this key was default. I don't know which hotkey makes this problem.
4. 
![C9fu0dTBJ8](https://user-images.githubusercontent.com/107253953/230508264-fa374fba-0823-47c4-8ff5-97ab43b07fcf.png)
This is my all installed addons. It's not much, isn't it?
5. I will do uninstalling the addon, closing and reopening Blender and reinstalling, reenabling. And check that it works or not
6. And last, I'll check every one of the hotkeys if RMN addon works when I make it default key.

**Comment by huRwww** [comment]
Oh, it works.
I've changed the keymap settings from my custom settings to 'Blender' setting.
And it works after turning back to my custom keymap settings, too.
Thank you very much.
