### ISSUE TITLE
Azerty

### ISSUE THREAD

**Issue by Frakatchoo** [SpectralVectors/RightMouseNavigation#19]
Nice Addon !
But any chance to change WASD to ZQSD (for Azerty keyboards) to move ?
Thanks.

**Comment by SpectralVectors** [comment]
The addon uses Blender's built-in Walk Navigation, so you can just change the keys that it uses in the keymap.

Go to:
Edit > Preferences > Keymap > 3D View > View3D Walk Modal
and set Forward, Backward etc to ZQSD
