### ISSUE TITLE
updating to a new blender version with this addon installed and enabled causes bizarre mouse button behavior

### ISSUE THREAD

**Issue by staticanimal** [SpectralVectors/RightMouseNavigation#21]
this has happened multiple times now. most recent instance was me updating from blender 3.6 to 4.0. exact same issue happened after updating from 3.4 to 3.6 months ago as well.

issue: after updating, middle mouse click stops working entirely. right clicking just once anywhere in a 3d viewport will cause the program to get stuck in lookaround mode and render the entire ui unclickable at which point a program restart becomes necessary.

how to reproduce: open blender install to copy settings to > load blender x.x settings

looking into this issue more it seems that the addon completely erases every keybind in view3d walk modal and every global keybind in preferences > keymap > 3d view, object mode, mesh, curve, armature, metaball, lattice, font, pose, vertex paint, weight paint, image paint and sculpt.
manually restoring the settings works for most of them, but upon closing and reopening the program, all global keybinds for node editor and 3d view are erased again.

a functional fix seems to be to delete the addon from the previous blender version, load the new blender version, import settings from the old version and then reinstall the addon in the new version.

**Comment by SpectralVectors** [comment]
Hi, unfortunately these are known issues, and I thought that I had addressed them, but clearly they have persisted through multiple versions.

I have narrowed it down to the keymap registration, which seems to be erasing large chunks of Blender's keymap which correspond to all the areas of the keymap that I'm adjusting, but apparently I'm just applying bandaid solutions that don't fix the underlying cause.

Thank you for creating the issue, I will update this when I have a solution.

**Comment by nurb2kea** [comment]
I just stumbled over your @SpectralVectors script and was interested.
But couldn't get it to work with macOS silicon blender 4.0 - 4.1 & my ALT + left/middle/right mouse buttons for navigation setup. 
Just to let you know, that Mac and 'Alt'-navigation needs a solution, if you intend to provide this functionality to Mac users as well.

**Comment by Ares9323** [comment]
I've tried to understand why my left click wasn't working for the last hour and I finally identified that the issue is this addon (that I love and I don't want to live without ♥️). I noticed that if you restore all the default keybindings and then activate the addon, everything works fine, the issue is that when you restart blender you are no longer able to left click to select anything.

**Comment by Ares9323** [comment]
I solved this issue Updating to 4.1.1 release candidate,  apparently there was something wrong in the 4.1 release (other things weren't working for me)

**Comment by SpectralVectors** [comment]
@staticanimal @nurb2kea @Ares9323 
I have created a new release that I believe fixes all the above issues:
https://github.com/SpectralVectors/RightMouseNavigation/releases/tag/keymap-fix-release

Of course, I've thought that before, so I'm leaving the issue open for now.
Let me know if your issues persist and I'll take a look at another solution, but I _think_ I've got it this time.
_(nervous sweating)_

**Comment by Ares9323** [comment]
I love you 💘

It seems to be working for me, let's hope it lasts!
If you want a free sample of [my Blender plugin](https://blendermarket.com/products/blender2c2i) you just have to ask!

**Comment by SpectralVectors** [comment]
@Ares9323 Sure, that sounds like a really good idea, it is a little frustrating that you can't just open those files with Blender, but you have to open Blender and then import them. Really interesting approach to the issue!

@staticanimal @nurb2kea I'm going to mark this issue as closed for now. 
If your issues persist, please open another and I will see what I can do.
AFAIK this update should fix all the issues with keys not working, or parts of the keymap being erased, and should not cause any issues with updating to new Blender versions in the future.

Thanks for using the addon, and your patience with the bugs, and please let me know if it causes any issues in the future!

**Comment by Ares9323** [comment]
@SpectralVectors I sent you a coupon in DM on Linkedin, I couldn't find any other contact on all your linked pages 😅.
I've used Blender for a while and everything seems fine with your addon!

**Comment by SpectralVectors** [comment]
Lol, thanks, I didn't realize that I made myself so hard to track down!
That's great to hear, I think I might need to tweak it a little if I want to make sure that the new versions are backwards compatible, but I think I finally killed the keymap bug!
Thanks again!
