### ISSUE TITLE
Distance Threshold seemingly not working

### ISSUE THREAD

**Issue by ettiSurreal** [SpectralVectors/RightMouseNavigation#22]
The tooltip says it's how far you have to move the mouse to trigger navigation, but it begins immediately after pressing it, without even moving the mouse. Also creates a slightly annoying flicker when quickly pressed.

**Comment by ettiSurreal** [comment]
Definitely doesn't seem like a 4.1 breakage, checking it in 4.0.2 and it doesn't work properly there either. it only seems to affect the distance before the context menu can no longer open.

Reset cursor doesn't seem to work at all either.

**Comment by SpectralVectors** [comment]
Yes, I should be clear:
I have a 4.1 issue to sort out: 
- users have reported Middle Mouse navigation is not working correctly

There are also existing bugs:
- keymap registration is bugged
- Distance Threshold is bugged (I'm not sure if this ever worked, but I'm also not sure why it didn't)
- Apparently reset cursor is also broken - this definitely did work, so it could be the result of an API change

I will let you know when I have an update for any of these issues.
Alternatively, you're welcome to submit a pull request if you know of a fix.
Thanks!

**Comment by SpectralVectors** [comment]
@ettiSurreal 
I was able to fix the Reset Cursor behavior, but the Distance Threshold didn't want to cooperate, so I just removed it.
Test release is available here: https://github.com/SpectralVectors/RightMouseNavigation/releases/tag/keymap-fix-release

**Comment by SpectralVectors** [comment]
I'm marking this issue as closed since the 'Distance Threshold' setting has been removed.
Feel free to create another issue if you find another bug, or you want the 'Distance Threshold' to be implemented.
Thanks for using the addon!
