### ISSUE TITLE
Option to disable zoom on click?

### ISSUE THREAD

**Issue by Farnsi** [SpectralVectors/RightMouseNavigation#24]
When you hold the right mouse button, it zooms out a little bit, when release, it zooms back in.

When you work close on vertices, this is annoying. Is there an option to disable it?

Thank you for the plugin, as an UE-Dev it is a live saver :D

**Comment by Farnsi** [comment]
My fault, i switched to perspective / orthographic projection, and than right click zooms.

**Comment by SpectralVectors** [comment]
Thanks for posting the resolution.
I think at one point there was a difference between viewport zoom level and navigation zoom, so I was going to mention that, but it doesn't seem to be an issue for me in Blender 4.1, so it may have been patched.
If you're a UE Dev you might also like:
https://github.com/spectralvectors/PreCam
https://github.com/spectralvectors/CommentBox
Thanks!
