### ISSUE TITLE
Few enhancement proposals

### ISSUE THREAD

**Issue by unreal-skif** [SpectralVectors/RightMouseNavigation#3]
- Right now it is possible to make a fast mouse move with RMB pressed and released very quickly. It causes menu spawning. Proposal to consider not only time RMB was pressed, but also the amount of pixels mouse was moved

 - Secondly - after every usage of RMB-navigation, the mouse cursor always set to the center of the viewport, it literally rages me. I can remember mouse coords but cannot restore it's position after the operator completed.

**Comment by Biaru** [comment]
I have created a pull request that addresses these issues. Or you can download from my fork :) - https://github.com/Biaru/RightMouseNavigation

**Comment by SpectralVectors** [comment]
Thanks for the code, I've merged it into the main branch, and I'll mark this issue closed.
The mouse cursor resetting wasn't enraging me, but the context menu showing up at the center of the screen every time DEFINITELY WAS!
Thank you! 👍
