### ISSUE TITLE
Left Click Select/Deselect stopped working?

### ISSUE THREAD

**Issue by XodrocSO** [SpectralVectors/RightMouseNavigation#31]
Greetings.

I was working in Blender 4.02 and version 2.00 of RightMouseNavigation without issues.  

After a long break from Blender, I found that I couldn't deselect or select with left mouse and the only way to get it working again was to go to keymap settings and restore, which seems to break RightMouseNavigation.  If I disable RMN, restart and re-enable it, it works again but selection is broken again.

Only thing I did was update my blender launcher and install Blender 4.2 as well (which I'll probably have to make a separate ticket for).  Don't know how that could break anything, but grasping at straws. 

Thanks, really is an awesome plugin.

**Comment by XodrocSO** [comment]
Just found the closed ticket talking about this, heh.    Odd that I never had problems going from 3.x to 4.0.  

Do I just need to use the new version in Blender 4.0.2?

**Comment by SpectralVectors** [comment]
Blender changed how some things work in 4.2, so you'll need the latest version there.

If you have an old version installed, you can uninstall it - the new version is available from within Blender via Extensions:

Open Blender
Edit > Preferences > Get Extensions > Right Mouse Naviation > Install

So, compatibility-wise:
Blender 4.2 - use v2.3.9 from the Extensions
Blender 4.1 - use v2.2 from the Releases page on Github
Blender 4.0 - use v2.1 from Releases
Blender 3.0 and under - use v2.0 from Releases

**Comment by XodrocSO** [comment]
2.1 worked perfectly with 4.0, thanks!   Sticking with it until I feel an actual need for new features.
