### ISSUE TITLE
register_class(...): already registered as a subclass 'RightMouseNavigationPreferences'

### ISSUE THREAD

**Issue by Yujiro-Ito** [SpectralVectors/RightMouseNavigation#33]
**What Went Wrong?**
When I import addon from extensions window import error with occurred error.

**How Can We Recreate the Problem?**
1. Open "Preferences>Get extension"
2. Search "Right Mouse Navigation"
3. Import addon
4. Open "Preferences>Addon"
5. Enable "Right Mouse Navigation"
6. Error occurred "register_class(...): already registered as a subclass 'RightMouseNavigationPreferences'"

**What Should Have Happened**
Expected success addon enable.

**Screenshots**
Sorry in Japanese.
![image](https://github.com/user-attachments/assets/073ca1c7-9e7d-430c-95e6-e35694f8ef40)

**System Information:**
- OS: Win10
- Blender Version 4.2.1 LTS
- Addon Version 2.3.9

**Comment by roguesleipnir** [comment]
The Add-On might have failed to import properly. 
One cause is if you are using a custom KeyMap that's not the default KeyMap named "Blender".
I also encountered this a few days ago too.

**Comment by Yujiro-Ito** [comment]
When I keymap turn to default to problem solved.
Thanks a lot.

**Comment by SpectralVectors** [comment]
@roguesleipnir @Yujiro-Ito Thanks for bringing this to my attention, I'll double check the code around the keymaps to see if I can avoid this issue in the future!
