### ISSUE TITLE
It doesn't work on Mac？

### ISSUE THREAD

**Issue by zenithknight** [SpectralVectors/RightMouseNavigation#7]
Hi, I'm using M1 Mac

Just right-click to report

  File “……Application Support/Blender/2.93/scripts/addons/RightMouseNavigation.py", line 134, in invoke
    ctypes.windll.user32.GetCursorPos(ctypes.byref(cursor))
AttributeError: module 'ctypes' has no attribute 'windll'

location: <unknown location>:-1

**Comment by SpectralVectors** [comment]
Hi, the addon currently uses Ctypes (python library) to fake a right mouse press using Win dll. I'm not sure if Ctypes supports Mac/Linux, but it might be possible to modify it to work on Mac, unfortunately, I don't have one to test with.
You can fork it and replace that line with the Mac equivalent, if there is one, but I'm not sure how Ctypes interacts with Mac OS, sorry!

**Comment by SpectralVectors** [comment]
Hi guategeek, I will try to help:

1 - I couldn't get ernestp's to work either

2 - Whitebox looks like it's implementing the old way I used to do it, just by altering the keymap. You can try to do this manually yourself, but you will have to do it in several keymaps (Object, Edit, Weight Paint, Vertex Paint etc.) if you want it to work everywhere. Basically, you bind 'view3d.walk' to Right Mouse 'Click Drag' and Walk Modal Confirm to Right Mouse 'Release'. That should do it, but depending on how you set it up you may either lose context menus, or have buggy context menu support.

3 - You've probably already tried this, but the traditional way to install is by going to the main page, going to where it says Releases, and clicking on '1.8 Bug fixes and tidying up', then, on that page, download RightMouseNavigation.zip
Then, in Blender, go to Edit > Preferences > Addons > Install, and install RightMouseNavigation.zip
If that doesn't work, or if you've already tried it, then, before clicking Install, open the System Console, Window > Toggle System Console, and copy the error message here, and maybe that can help out.

It's designed for people who use left-click select, in case you're a right click selecter. I can't think of anything else that would impact it at the moment.

**Comment by guategeek** [comment]
I have started with a clean Blender install and it works, so I'm slowly adding my other plugins to see what was stopping it from working before. Thanks for the great plugin!

**Comment by SpectralVectors** [comment]
Hi zenithknight, old post, I know, but I believe the RightMouseNavigation addon should now work on Mac.
I'm closing the issue, feel free to open a new one if it doesn't work as expected.
Thanks!
