### ISSUE TITLE
UnrealRightClick not working if I open a .blend file

### ISSUE THREAD

**Issue by Ares9323** [SpectralVectors/RightMouseNavigation#8]
Working fine when I open blender then open a .blend file, if I double click the file the addon doesn't work.
If I open the addons section it's marked as enabled, if I disable it and then re-enable it, then it works fine.

I made a script to open other extensions as default with blender, if I double click an .fbx, .obj, etc it works fine, the problem shows up only with .blend files

Before opening this issue I tested multiple times with clean installations of blender 2.83 and 2.92

How to replicate:
-Open blender (factory settings)
-Install this addon only and activate it
-Save the file with the default cube
-Save startup file
-Close blender
-Double click the previously saved file
-Extension should not work

Thank you for your amazing work!
I'm glad you suggested me this addon, it's lighter than Blunder and it's just perfect for my needs

**Comment by SpectralVectors** [comment]
Thanks for the detailed report, I tried your steps, and I was able to replicate the bug on my end, now it's just a matter of figuring out why it's happening!?

I had another bug report a while ago that I wasn't able to reproduce on my machine, so I'm glad that, at least in this case, I can actually experience, and hopefully fix the behaviour. 

I'm still not back in the swing of Blender/Python/Unreal quite yet, I have a few more projects at work that I have to finish up first, but this is going on the TODO list!

What a weird bug!

**Comment by Ares9323** [comment]
Thank you for your answer, i'm "happy" you have been able to reproduce it.
In the meantime I've been able to temporarily solve it by opening .blend files with my program and launch a python command after the file is imported.
I used addon_utils.disable("UnrealRightClick") and addon_utils.enable("UnrealRightClick") to toggle it and now it seems to work fine (obviously you have to import addon_utils first otherwise it won't work)

This kind of behaviour makes me think that the extension loads before the file and something conflicts with it (maybe it happens with other addons too but yours is the only one I always use so that's why I noticed it).
The fact that this is happening only with .blend files and not with other formats may verify because they contain settings about the interface and there's a problem saving the extension status when the file is closed.
I also noticed that if you disable an extension by python it's not updated on the addon interface (checkbox remains checked) so it's not reliable to see if it's active.

I hope I've been useful, have a nice day!

**Comment by edin-purkovic** [comment]
I believe that enabling "Auto Run Python Scripts" should fix your issue:
![image](https://user-images.githubusercontent.com/12642134/118811272-179dc280-b8ad-11eb-91c5-72a152eeb740.png)

**Comment by SpectralVectors** [comment]
Hi edin and Ares, unfortunately "Auto Run Python" didn't fix it, but I managed to finally get rid of the bug by registering keymaps to the USER instead of the ADDON.
Thanks!
