### ISSUE TITLE
Disabling the add-on breaks right click + throws errors

### ISSUE THREAD

**Issue by josephniet** [SpectralVectors/RightMouseNavigation#9]
![image](https://user-images.githubusercontent.com/4440633/128642437-e41129e1-fb3a-43a6-8fec-b3c747fc8942.png)

blender 2.93.1
Win10

I can't right click at all after disabling the add-on.

**Comment by josephniet** [comment]
Manually went & hit restore under Preferences > Keymap which has worked.

**Comment by SpectralVectors** [comment]
Hi jospehniet, thanks for bringing the error to my attention, apologies for the delay in getting to fixing it, but I'm happy to say that it's fixed now, you can check release 1.7 for the bugfix.
